"""Resource-tier classification computed from CommonVoiceLID line counts (spec §11)."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Literal, cast

ResourceTier = Literal["high", "mid", "low", "unknown"]

_TIERS_PATH = Path(__file__).parent / "_tiers.json"


@lru_cache(maxsize=1)
def _load_tiers() -> dict[str, str]:
    if not _TIERS_PATH.exists():
        return {}
    return json.loads(_TIERS_PATH.read_text())


def tier_for(lang_code: str) -> ResourceTier:
    """Return the resource tier for a BCP-47 code.

    Reads from `src/language_id/languages/_tiers.json`, regenerated by the
    `language-id compute-tiers` CLI subcommand. Returns "unknown" if the file
    has not been generated yet or the language is missing.
    """
    return cast(ResourceTier, _load_tiers().get(lang_code, "unknown"))


def compute_tiers_from_counts(
    counts: dict[str, int],
    thresholds: dict[str, int],
) -> dict[str, ResourceTier]:
    """Compute per-language tiers from line counts and configured thresholds.

    `thresholds` keys: "high", "mid", "low". A language with `n >= thresholds["high"]`
    is "high", `n >= thresholds["mid"]` is "mid", otherwise "low".
    """
    high = thresholds["high"]
    mid = thresholds["mid"]
    result: dict[str, ResourceTier] = {}
    for lang, n in counts.items():
        if n >= high:
            result[lang] = "high"
        elif n >= mid:
            result[lang] = "mid"
        else:
            result[lang] = "low"
    return result
