name: logreg
kind: trained
implementation: language_id.models.trained.logreg:LogRegModel
version: "0.0.1"
vectorizer:
  analyzer: char_wb
  ngram_range: [2, 5]
  min_df: 2
  max_features: 2_000_000
  sublinear_tf: true
classifier:
  C: 1.0
  max_iter: 200
  n_jobs: -1
  solver: saga
training:
  random_state: 42
