"""Markdown table generation from result artifacts (spec §12.3)."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from language_id.reporting.figures import _latest_eval_per_model_dataset, _read_runs_jsonl

_REPO_ROOT = Path(__file__).resolve().parents[3]


def _df_to_markdown(df: pd.DataFrame) -> str:
    if df.empty:
        return "_(empty)_"
    headers = list(df.columns)
    rows = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for _, row in df.iterrows():
        rows.append(
            "| "
            + " | ".join(
                f"{v:.4f}" if isinstance(v, float) else str(v) for v in row.tolist()
            )
            + " |"
        )
    return "\n".join(rows)


def _build_results_md(results_dir: Path, figures_dir_rel: Path) -> str:
    runs = _read_runs_jsonl(results_dir / "runs.jsonl")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out: list[str] = [
        "# Results",
        "",
        "<!--",
        "Regenerated by `language-id report` from artifacts in `results/`.",
        "Do not edit by hand — your changes will be overwritten on the next report.",
        "-->",
        "",
        f"_Last regenerated: {now}._",
        "",
    ]

    if not runs:
        out += ["_No runs yet. Run an eval / training command to populate this page._"]
        return "\n".join(out) + "\n"

    leaderboard_png = (results_dir.parent / figures_dir_rel / "leaderboard.png")
    if leaderboard_png.exists():
        out += ["## Leaderboard", "", f"![Leaderboard]({figures_dir_rel.as_posix()}/leaderboard.png)", ""]
    else:
        out += ["## Leaderboard", ""]

    df = _latest_eval_per_model_dataset(runs)
    if not df.empty:
        keep_cols = [c for c in ("model", "dataset", "macro_f1", "n", "run_id") if c in df.columns]
        out += [_df_to_markdown(df[keep_cols]), ""]

    # Experiment-specific sections
    exp_dir = results_dir / "experiments"
    if exp_dir.exists():
        exp3_de = sorted(exp_dir.glob("exp3_data_efficiency_*.parquet"), key=lambda p: p.stat().st_mtime, reverse=True)
        if exp3_de:
            out += ["## Experiment 3 — Data-efficiency curve", ""]
            plot_rel = figures_dir_rel.as_posix() + "/exp3_data_efficiency.png"
            if (results_dir.parent / plot_rel).exists():
                out += [f"![Data-efficiency curve]({plot_rel})", ""]
            de_df = pd.read_parquet(exp3_de[0])
            if not de_df.empty:
                agg = (
                    de_df.groupby(["model", "n"])[["accuracy", "macro_f1"]]
                    .mean()
                    .reset_index()
                )
                out += [_df_to_markdown(agg), ""]

        exp3_llm = sorted(exp_dir.glob("exp3_llm_few_shot_*.parquet"), key=lambda p: p.stat().st_mtime, reverse=True)
        if exp3_llm:
            out += ["## Experiment 3 — LLM zero/few-shot on Marma", ""]
            llm_df = pd.read_parquet(exp3_llm[0])
            out += [_df_to_markdown(llm_df), ""]

        exp5 = sorted(exp_dir.glob("exp5_summary_*.parquet"), key=lambda p: p.stat().st_mtime, reverse=True)
        if exp5:
            out += ["## Experiment 5 — Cross-benchmark", ""]
            exp5_df = pd.read_parquet(exp5[0])
            keep = [c for c in ("model", "macro_f1", "n", "run_id") if c in exp5_df.columns]
            out += [_df_to_markdown(exp5_df[keep]), ""]

    out += ["## Figures", "", f"All committed figures live in [`{figures_dir_rel.as_posix()}/`]({figures_dir_rel.as_posix()}/)."]
    return "\n".join(out) + "\n"


def _build_reconciliation_md(overrides_path: Path) -> str:
    base = [
        "# Language code reconciliation",
        "",
        "All loaders and parsers normalize to **BCP-47** (Common Voice standard). When a dataset or model emits a non-standard code that `langcodes.standardize_tag` cannot resolve, we apply a versioned override table:",
        "",
        "- Source: [`src/language_id/languages/_mapping_overrides.yaml`](https://github.com/Mozilla-Data-Collective/language-id/blob/main/src/language_id/languages/_mapping_overrides.yaml)",
        "- Generated table below is rebuilt by `language-id report`.",
        "",
        "## LLM free-text parsing",
        "",
        "LLM responses are passed through `parsing/llm_output.py`:",
        "",
        '1. Strip common prefixes/suffixes (`"The language is..."`, `"Language:"`, trailing punctuation/quotes).',
        '2. Try as a BCP-47 tag via `to_bcp47` (covers `"en"`, `"zh-Hans"`, etc).',
        '3. Look up by name via `langcodes.find()` (handles `"Spanish"`, `"español"`, `"Castilian"`).',
        "4. Hand-written alias table.",
        "5. Mark unparseable; logged for inspection.",
        "",
        "## Override mappings",
        "",
    ]
    overrides = yaml.safe_load(overrides_path.read_text()) or {} if overrides_path.exists() else {}
    mappings = (overrides.get("mappings") or {}) if isinstance(overrides, dict) else {}
    if not mappings:
        base.append("_No overrides registered yet._")
    else:
        base.append("| Source code | Canonical BCP-47 |")
        base.append("| --- | --- |")
        for src, dst in sorted(mappings.items()):
            base.append(f"| `{src}` | `{dst}` |")
    return "\n".join(base) + "\n"


def regenerate_all(results_dir: Path, docs_dir: Path) -> list[Path]:
    """Regenerate `docs/results.md` and `docs/language-code-reconciliation.md`."""
    results_dir = Path(results_dir)
    docs_dir = Path(docs_dir)
    written: list[Path] = []

    results_md = _build_results_md(results_dir, figures_dir_rel=Path("figures"))
    results_path = docs_dir / "results.md"
    results_path.write_text(results_md)
    written.append(results_path)

    overrides_path = (
        _REPO_ROOT / "src" / "language_id" / "languages" / "_mapping_overrides.yaml"
    )
    reconciliation_md = _build_reconciliation_md(overrides_path)
    reconciliation_path = docs_dir / "language-code-reconciliation.md"
    reconciliation_path.write_text(reconciliation_md)
    written.append(reconciliation_path)

    return written
